version: "3.8"

services:
  waterbox:
    image: ghcr.io/ahayden/waterbox:base
    hostname: waterbox
    environment:
      TERM: "xterm-color"
    extra_hosts:
      - "base:127.0.0.1"
    container_name: waterbox
    volumes:
      - data:/data

